export const AUTHENTICATION_FLOW = 'AUTHENTICATION_FLOW';
export const LOGOUT_FLOW = 'LOGOUT_FLOW';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
export const AUTHENTICATION_PENDING = 'AUTHENTICATION_PENDING';
export const LOGOUT = 'LOGOUT';

export const SIGN_UP_FLOW = 'SIGN_UP_FLOW';
export const SIGN_UP_PENDING = 'SIGN_UP_PENDING';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const VERIFYING_TOKEN_FLOW = 'VERIFYING_TOKEN_FLOW';
export const VERIFYING_TOKEN_PENDING = 'VERIFYING_TOKEN_PENDING';
export const TOKEN_INVALIDATE = 'TOKEN_INVALIDATE';
export const TOKEN_VALID = 'TOKEN_VALID';

export const ADD_POST_FLOW = 'ADD_POST_FLOW';
export const ADD_POST_PENDING = 'ADD_POST_PENDING';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';

export const RETRIEVE_POSTS_FLOW = 'RETRIEVE_POSTS_FLOW';
export const RETRIEVE_POSTS_PENDING_STATUS = 'RETRIEVE_POSTS_PENDING_STATUS';
export const RETRIEVE_POSTS_SUCCESS = 'RETRIEVE_POSTS_SUCCESS';
export const RETRIEVE_POSTS_FAILURE = 'RETRIEVE_POSTS_FAILURE';

export const RETRIEVE_POST_FLOW = 'RETRIEVE_POST_FLOW';
export const RETRIEVE_POST_SUCCESS = 'RETRIEVE_POST_SUCCESS';
export const RETRIEVE_POST_PENDING = 'RETRIEVE_POST_PENDING';
export const RETRIEVE_POST_FAILURE = 'RETRIEVE_POST_FAILURE';

export const REDIRECT_AFTER_LOGIN = 'REDIRECT_AFTER_LOGIN';
