export const AUTHENTICATION_FLOW = 'AUTHENTICATION_FLOW';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
export const AUTHENTICATION_PENDING = 'AUTHENTICATION_PENDING'